version: "2"
services:
  jenkins:
    container_name: jenkins
    build:
      context: image
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - "./jenkins_home:/var/jenkins_home"
      - "../repos:/var/repos"
